# ---------- DB (MySQL) ----------
spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/chatly_database?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DATASOURCE_USER:root}
spring.datasource.password=${DATASOURCE_PASSWORD:kartik@#$1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---------- REDIS (Railway via REDIS_URL) ----------
# Local pe Redis na ho to bhi theek, bas OTP nahi chalega
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.timeout=60000

# IMPORTANT: yahan ssl.enabled mat likho, kyunki rediss:// scheme se
# Spring khud SSL enable kar deta hai

logging.level.org.springframework.boot.autoconfigure=INFO

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.upload.dir=uploads
app.upload.max-size-bytes=5242880

logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG

spring.data.redis.lettuce.shutdown-timeout=0
spring.data.redis.lettuce.client-name=

